name: gupt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyter
  - pip:
    - langchain==0.3.26
    - langchain-openai==0.3.27
    - langchain-community==0.3.27
    - langchain-core==0.3.68
    - langchain-chroma==0.1.4
    - langchain-text-splitters==0.3.8
    - openai==1.95.1
    - chromadb==0.5.23
    - gradio==5.22.0
    - python-dotenv==1.1.1
    - numpy==1.26.4
    - pandas==2.2.3
    - rouge-score==0.1.2
    - sentence-transformers==3.3.0
    - bert-score==0.3.13
    - scikit-learn==1.5.2
    - typing-extensions==4.12.2
    - pydantic==2.11.7
    - pypdf==5.1.0
    - requests==2.32.3
    - urllib3==2.2.3
    - charset-normalizer==3.4.0
    - posthog==3.7.2 